### ISSUE TITLE
Second header, can just be a h2

### ISSUE THREAD

**Issue by teenie-quaggard** [FACxBeamery/week-1-project#30]
I think you *can* have a second header here, but it makes the page a big harder to read. Another way might be to remove the header and leave the h2.
![Screen Shot 2019-09-13 at 09 16 58](https://user-images.githubusercontent.com/37771591/64847604-44dd9c00-d607-11e9-808d-0b11d3ae2a7d.png)

**Comment by lyndseysc** [comment]
remove header with pull request #44
