### ISSUE TITLE
Overlap of image after submit

### ISSUE THREAD

**Issue by teenie-quaggard** [FACxBeamery/week-1-project#40]
Maybe you've caught this already, there's some text overlap when the information is rendered!
![Screen Shot 2019-09-13 at 10 48 38](https://user-images.githubusercontent.com/37771591/64853798-1c0fd380-d614-11e9-9962-6f7427c2a35b.png)

**Comment by lyndseysc** [comment]
most recent pull request #33 was not accepted, fixed now
